server:
  port: 8000

spring:
  application:
    name: spring-security
  datasource:
    username: root
    password: 259359
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.liang.springsecurity.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug